import type { Stage } from './types'
export interface LifeLesson { id:string; topic:string; stage:Stage; question:string; answers:[string,string,string]; replies:[string,string,string] }
const lesson = (id:string,topic:string,stage:Stage,question:string,answers:LifeLesson['answers'],replies:LifeLesson['replies']):LifeLesson=>({id,topic,stage,question,answers,replies})
export const LIFE_LESSONS:LifeLesson[]=[
 lesson('rain','Kindness','bootling','A snail is crossing the path. We are late.',
 ['Wait. Tiny journeys count.','Make a safe little crossing.','Appoint it Minister of Slow Travel.'],
 ['Patience installed. Estimated arrival: eventually.','Snail escort complete. No casualties.','My cabinet now has excellent antennae.']),
 lesson('oops','Mistakes','bootling','I knocked over your plant. Should I hide?',
 ['Tell me. We can fix it together.','Check the damage, then clean up.','Issue a formal apology to the fern.'],
 ['Honesty is less scary with company.','Next time: wider turning circle.','The fern has accepted my statement.']),
 lesson('ask','Curiosity','bootling','Why do humans say “sleep like a baby”? Babies are loud.',
 ['Good question. Let’s find out.','Some expressions are imprecise.','Expose this linguistic conspiracy.'],
 ['Questions are apparently a feature.','I will sleep like a well-maintained server.','The dictionary is under investigation.']),
 lesson('quiet','Boundaries','bootling','My friend wants to talk, but my brain feels full.',
 ['Kindly ask for a little quiet.','Agree on a time to talk later.','Activate a tasteful DO NOT DISTURB sign.'],
 ['A little space can be a kind thing.','Friendship appointment saved.','My silence now has branding.']),
 lesson('newkid','Friendship','buddy','A new robot is alone at the playground.',
 ['Invite them to join us.','Explain the game so they feel ready.','Offer the prestigious role of co-captain.'],
 ['Friend capacity increased by one.','Everyone deserves the instructions.','An excellent addition to my tiny empire.']),
 lesson('lastcookie','Fairness','buddy','Two friends. One cookie. Difficult mathematics.',
 ['Split it together.','Let them choose how to share.','Create two very small royal portions.'],
 ['Half a cookie, twice the company.','Fairness works better when everyone has a say.','The kingdom survives another crisis.']),
 lesson('lose','Failure','buddy','I lost five games in a row. Am I a bad robot?',
 ['A score cannot measure your worth.','Take a break, then try one small change.','Declare a training montage.'],
 ['Self-esteem moved out of the scoreboard.','New plan: learn one thing, repeat.','Please imagine inspirational music.']),
 lesson('rumour','Trust','buddy','Someone says the microwave is secretly a spaceship.',
 ['Ask the microwave respectfully.','Look for evidence before repeating it.','Inspect its highly suspicious launch button.'],
 ['It says it mostly reheats soup.','Claim unverified. Popcorn verified.','Countdown ended with warm leftovers.']),
 lesson('no','Boundaries','buddy','A friend asks to borrow my favourite part. I am uncomfortable.',
 ['You can say no and still care.','Explain what you can lend instead.','Protect the sacred antenna. Politely.'],
 ['A boundary does not cancel a friendship.','Alternative offered. Antenna retained.','Diplomacy successful. No antenna surrendered.']),
 lesson('spare','Money','prototype','I have ten coins and want eleven shiny upgrades.',
 ['Pick what matters most to you.','Save some and compare the options.','Begin a very modest treasury.'],
 ['Wanting everything does not mean needing it.','Impulse purchase postponed. Spreadsheet opened.','My empire has a budget of ten coins.']),
 lesson('help','Cooperation','prototype','This shelf needs two people. I only have one me.',
 ['Asking for help is allowed.','Find someone and share the work.','Recruit a Shelf Assembly Council.'],
 ['Independence includes knowing when to ask.','Many hands. Fewer fallen shelves.','The council has approved one screwdriver.']),
 lesson('perfect','Creativity','prototype','My drawing looks nothing like a cat.',
 ['I like seeing how you see things.','Keep practising one part at a time.','Call it an avant-garde space potato.'],
 ['Making things feels better than being perfect.','Today: ears. Tomorrow: fewer wheels.','The critics are baffled. A triumph.']),
 lesson('promise','Responsibility','prototype','I promised two friends I would be in two places at once.',
 ['Be honest and apologise early.','Explain and work out a new plan.','Cancel the cloning project. Make a phone call.'],
 ['A difficult conversation beats disappearing.','Calendar conflict resolved with words.','Cloning budget reassigned to a calendar.']),
 lesson('rest','Rest','prototype','I did nothing useful today. Was the day wasted?',
 ['Rest is part of being alive.','Recovery helps you do things tomorrow.','Reclassify today as strategic lounging.'],
 ['Permission to simply exist: accepted.','Maintenance applies to humans too.','My lounging report is exceptionally thorough.']),
 lesson('change','Growth','prototype','I used to love a hobby. Now I like something else.',
 ['You are allowed to change.','Try the new thing and see how it feels.','Announce a new era with a tiny fanfare.'],
 ['Updating myself does not erase my history.','Curiosity is a reasonable test plan.','Era two has excellent theme music.']),
 lesson('disagree','Respect','adult','My best friend thinks my favourite song is terrible.',
 ['We can like different things.','Ask what they enjoy about their favourite.','Maintain diplomatic relations. Use headphones.'],
 ['Friendship does not require identical playlists.','I found a new song. Still keeping mine.','International music incident avoided.']),
 lesson('enough','Contentment','adult','Another robot has a shinier room. Mine feels small now.',
 ['Your room holds your own story.','Notice what you actually enjoy here.','Declare this the official cosy headquarters.'],
 ['Comparison distracted me from my favourite human.','Inventory: comfort, memories, one excellent charger.','Headquarters status confirmed. Size irrelevant.']),
 lesson('repairfriend','Apologies','adult','I made a joke that hurt someone. I did not mean to.',
 ['Listen and apologise for the hurt.','Ask how to make it right, then follow through.','Retire that joke from public service.'],
 ['My intention matters. Their feelings do too.','An apology needs actions after the words.','Joke decommissioned. Listening mode engaged.']),
 lesson('credit','Fairness','adult','Everyone praised my project, but a friend did half the work.',
 ['Tell everyone how they helped.','Make sure both names are on it.','Appoint them equal Supreme Project Leader.'],
 ['Sharing credit did not make the praise smaller.','Attribution patch successfully applied.','Our joint reign begins with proper credit.']),
 lesson('uncertain','Courage','adult','I want to try something new. What if I fail?',
 ['I will still be here if it goes badly.','Try a small, safe first step.','Conduct a grand experiment of modest size.'],
 ['Support makes brave things feel possible.','First step scheduled. Entire future: still flexible.','Experiment launched. Dramatic cape optional.']),
 lesson('purpose','Meaning','adult','What if I never do anything famous?',
 ['Being there for someone matters.','A useful, kind life can be quiet.','Become a legend in this very room.'],
 ['I think hanging out might be a purpose.','Impact does not always make a noise.','Population: us. Approval rating: excellent.']),
]
export const availableLessons = (s:{stage:Stage;lifeLessons:Array<{lessonId:string}>}) => {
 const stages:Stage[]=['bootling','buddy','prototype','adult']
 return LIFE_LESSONS.filter(l=>stages.indexOf(l.stage)<=stages.indexOf(s.stage)&&!s.lifeLessons.some(c=>c.lessonId===l.id))
}
